config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'scrape', to: 'welcome#scrape'

  root 'welcome#index'

  resources :trainers do
    collection do
      post :import_official
      post :import_societe
      get :crawl_for_emails
      get :search
    end
    member do
      get :skip
    end
  end

end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
	require 'nokogiri'
	require 'open-uri'

	after_initialize :init

	self.per_page = 50

	def init
		self.crawled_for_email ||= false
	end

	def self.to_csv(options = {})	
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |trainer|
				csv << trainer.attributes.values_at(*column_names)
			end
		end
	end

	def self.import_official(file)
		csv_text = File.read(file.path)
		csv = CSV.parse(csv_text, :headers => true)
		csv.each do |row|
			raw_data = row.to_hash
			if Trainer.where(siren: raw_data["siren"]).empty?
				Trainer.create!(raw_data.slice("siren", "sigle", "effectif"))
			end
		end
	end

	def self.import_societe(file)
		# open CSV file
		csv_text = File.read(file.path)
		csv = CSV.parse(csv_text, :headers => true, quote_char: "\x00")

		# read rows
		csv.each do |row|
			raw_data = row.to_hash
			# parse "rens_jur" into Dénomination, Présence d'adresse, Adresse, Code Postal, Présence du téléphone, Siren, Activité, Forme juridique, Type de date de création, Date de création
			rens_jur = /Dénomination (.*?)( Adresse (.*?(\d{5}).*?)|)( Téléphone .*?|) SIREN (.*?) SIRET .*? Description de l'activité de l'entreprise (.*?) Forme juridique (.*?) (Date création entreprise|Date immatriculation RCS) (.*?) Tranche/.match(raw_data["rens_jur"])
			if rens_jur
				trainer = Trainer.where(siren: rens_jur[6]).first
				trainer.update(denomination: rens_jur[1])
				trainer.update(adresse: rens_jur[3])
				trainer.update(code_postal: rens_jur[4])
				trainer.update(activite: rens_jur[7])
				trainer.update(forme_juridique: rens_jur[8])
				trainer.update(date_de_creation: rens_jur[10])

				trainer.update(lien_societe: raw_data["_pageUrl"])

				# parse "dirigeant" into sexe_dirigeant, nom_dirigeant
				dirigeant = /Depuis.*?\d{4} (M|MME) (.*?) En savoir plus/.match(raw_data["dirigeant"])
				if dirigeant
					trainer.update(sexe_dirigeant: dirigeant[1])
					trainer.update(nom_dirigeant: dirigeant[2])
				end
			end
		end
	end

	def self.crawl_for_emails(crawls_number)
		i = 1
		validated_emails_count = 0

		# list OFs that have a dirigeant, that haven't already been crawled, and that are in Paris in priority
		trainers = Trainer.where.not(nom_dirigeant: nil, crawled_for_email: true).select("*, CASE WHEN trainers.code_postal like '75%' THEN 0 ELSE 1 END AS trainers_order").order("trainers_order ASC").limit(1000)

		while i <= crawls_number.to_i do
			trainer = trainers[i-1]

			# track progress in console
			logger.info "Request #{i} is SIREN #{trainer.siren}"

			# find the domain of the company using Bing's first search result on query 'sigle'
			domain = trainer.find_domain

			unless domain.nil?
				# build email address by removing accents, replacing spaces by dots, and using "@domain"
				email = I18n.transliterate(trainer.nom_dirigeant).gsub(/ /,'.')+'@'+domain

				# test email address with QuickEmailVerificationAPI
				if try_address(email) == 'valid'
					trainer.email_dirigeant = email
					validated_emails_count+=1
				end
			end

			# remember that OF has been crawled, save, and move to next
			trainer.crawled_for_email = true
			trainer.save
			i+=1
		end



		return validated_emails_count
	end

	# extracts the domain name using BING's first search result.
	# sends nil if can't find it.
	def find_domain
		doc = Nokogiri::HTML(open('http://www.bing.com/search?' + {q: self.sigle}.to_query))
		url_block = doc.css('.b_algo cite').first

		return nil if url_block.nil?

		md = /\.(.*?\.[[:alpha:]]{2,4})($|\/| ›)/.match(url_block.content)

		return nil if md.nil?

		return md[1]
	end

	def self.try_address(email)
		# call QuickEmailVerification API
		begin
			doc = open("http://api.quickemailverification.com/v1/verify?apikey=09f7ff4254cb0fca02a614bd12611ed94585ab4fa90b04a7476e31c8381c&email=" + email)
		rescue Net::ReadTimeout
			logger.info "QuickEmailVerification TimeOut"
			return "TimeOut"
		end

		
		# convert to hash
		response = JSON.parse(doc.read)

		# read result
		return response['result']
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :set_trainer, only: [:show, :edit, :update, :destroy, :skip]

  # GET /trainers
  # GET /trainers.json
  def index
    @trainers = Trainer.paginate(:page => params[:page]).order(email_dirigeant: :desc, crawled_for_email: :desc)
    respond_to do |format|
      format.html
      format.csv { send_data Trainer.all.to_csv}
    end
  end

  # GET /trainers/1
  # GET /trainers/1.json
  def show
  end

  # GET /trainers/new
  def new
    @trainer = Trainer.new
  end

  # GET /trainers/1/edit
  def edit
  end

  # POST /trainers
  # POST /trainers.json
  def create
    @trainer = Trainer.new(trainer_params)

    respond_to do |format|
      if @trainer.save
        format.html { redirect_to @trainer, notice: 'Trainer was successfully created.' }
        format.json { render :show, status: :created, location: @trainer }
      else
        format.html { render :new }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  def import_official
    Trainer.import_official(params[:file])
    redirect_to root_path, notice: "Liste importée."
  end

  def import_societe
    Trainer.import_societe(params[:file])
    redirect_to root_path, notice: "Societés importées."
  end

  def crawl_for_emails
    validated_emails_count = Trainer.crawl_for_emails(params[:crawls_number])
    redirect_to root_path, notice: validated_emails_count.to_s + " emails ajoutés sur " + params[:crawls_number].to_s
  end

  def search
    @trainer = Trainer.where(siren: params[:siren]).first
    redirect_to @trainer
  end

  def skip
    @trainer.crawled_for_email = true
    @trainer.save
    redirect_to root_path, notice: @trainer.siren + " a été sauté"
  end


  # PATCH/PUT /trainers/1
  # PATCH/PUT /trainers/1.json
  def update
    respond_to do |format|
      if @trainer.update(trainer_params)
        format.html { redirect_to @trainer, notice: 'Trainer was successfully updated.' }
        format.json { render :show, status: :ok, location: @trainer }
      else
        format.html { render :edit }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainers/1
  # DELETE /trainers/1.json
  def destroy
    @trainer.destroy
    respond_to do |format|
      format.html { redirect_to trainers_url, notice: 'Trainer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainer
      @trainer = Trainer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trainer_params
      params.require(:trainer).permit(:siren, :sigle, :effectif, :adresse, :nom_dirigeant, :email_dirigeant, :crawled_for_email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	require 'open-uri'
	require 'nokogiri'

	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>bédof</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/trainers/_form.html.erb
<%= form_for(@trainer) do |f| %>

  <div class="field">
    <%= f.label :siren %><br>
    <%= f.text_field :siren %>
  </div>
  <div class="field">
    <%= f.label :sigle %><br>
    <%= f.text_field :sigle %>
  </div>
  <div class="field">
    <%= f.label :effectif %><br>
    <%= f.number_field :effectif %>
  </div>
  <div class="field">
    <%= f.label :adresse %><br>
    <%= f.number_field :adresse %>
  </div>
  <div class="field">
    <%= f.label :nom_dirigeant %><br>
    <%= f.text_field :nom_dirigeant %>
  </div>
  <div class="field">
    <%= f.label :email_dirigeant %><br>
    <%= f.text_field :email_dirigeant %>
  </div>
  <div class="field">
    <%= f.label :crawled_for_email %><br>
    <%= f.check_box :crawled_for_email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trainers/edit.html.erb
<h1>Editing trainer</h1>

<%= render 'form' %>

<%= link_to 'Show', @trainer %> |
<%= link_to 'Back', trainers_path %>

app/views/trainers/index.html.erb
<%= notice %>

<h1>
  Liste des Organismes de Formation
</h1>
50 résultats par page, avec emails en haut
<p>
  <%= link_to "Retour à l'accueil", root_path %>
  <%= link_to "Télécharger au format CSV", trainers_path(format: "csv") %>
</p>
<table>
  <thead>
    <tr>
      <th>Siren</th>
      <th>Sigle</th>
      <th>Email Dirigeant</th>
      <th>Code Postal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainers.each do |trainer| %>
      <tr>
        <td><%= trainer.siren %></td>
        <td><%= trainer.sigle.truncate(50) %></td>
        <td><%= trainer.email_dirigeant %></td>
        <td><%= trainer.code_postal %></td>
        <td><%= link_to 'Voir', trainer %></td>
        <td><%= link_to 'Modifier', edit_trainer_path(trainer) %></td>
        <td><%= link_to 'Supprimer', trainer, method: :delete, data: { confirm: 'Es-tu sur?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @trainers %>

app/views/trainers/new.html.erb
<h1>New trainer</h1>

<%= render 'form' %>

<%= link_to 'Back', trainers_path %>

app/views/trainers/show.html.erb
<h1><%= @trainer.sigle %></h1>

<p>
  <strong>Siren:</strong>
  <%= @trainer.siren %>
</p>

<p>
  <strong>Sigle:</strong>
  <%= @trainer.sigle %>
</p>

<p>
  <strong>Lien Societe.com:</strong>
  <%= link_to @trainer.lien_societe, @trainer.lien_societe, target: "_blank" %>
</p>

<p>
  <strong>Dénomination:</strong>
  <%= @trainer.denomination %>
</p>

<p>
  <strong>Effectif:</strong>
  <%= @trainer.effectif %>
</p>

<p>
  <strong>Code postal:</strong>
  <%= @trainer.code_postal %>
</p>

<p>
  <strong>Adresse:</strong>
  <%= @trainer.adresse %>
</p>

<p>
  <strong>Activité:</strong>
  <%= @trainer.activite %>
</p>

<p>
  <strong>Forme Juridique:</strong>
  <%= @trainer.forme_juridique %>
</p>

<p>
  <strong>Date de Création:</strong>
  <%= @trainer.date_de_creation %>
</p>

<p>
  <strong>Sexe du Dirigeant:</strong>
  <%= @trainer.sexe_dirigeant %>
</p>

<p>
  <strong>Nom du dirigeant:</strong>
  <%= @trainer.nom_dirigeant %>
</p>

<p>
  <strong>Email du dirigeant:</strong>
  <%= @trainer.email_dirigeant %>
</p>

<p>
  <%= @trainer.crawled_for_email ? "Crawlé" : "Non Crawlé" %>
</p>

<%= link_to 'Edit', edit_trainer_path(@trainer) %> |
<%= link_to 'Back', trainers_path %>

app/views/welcome/index.html.erb
<%= notice %>

<h1>Yoooooo. Mon nom est bédof.</h1>
<p>Je suis une appli qui consolide et scrape le web pour assembler une BDD des organismes de formation en France.</p>
<p>
	Je contiens actuellement
	<strong>
		<%= Trainer.all.count %>
		sociétés,
		<%= Trainer.where.not(nom_dirigeant: nil).count %>
		dirigeants
		(<%= Trainer.where.not(nom_dirigeant: nil).where("code_postal like ?", "75%").count %> à Paris)
		,
		<%= Trainer.where(crawled_for_email: true).count %>
		crawls, 
		et
		<%= Trainer.where.not(email_dirigeant: [nil, '']).count %>
		emails validés.
	</strong>
</p>	
<p>Voici quelques actions :</p>
<ul>
	<li><%= link_to 'Voir la liste des OF', trainers_path %></li>
	<li><%= link_to "Télécharger au format CSV", trainers_path(format: "csv") %></li>
	<li>
		<%= form_tag search_trainers_path, :method => 'get' do %>
			Rechercher un OF par SIREN :
			<%= number_field_tag :siren, params[:siren] %>
			<%= submit_tag "Rechercher", :name => nil %>
		<% end %>
	</li>
	<li>
		<%= form_tag import_official_trainers_path, multipart: true do %>
			Importer depuis "Liste Officielle" via "Kimono" (CSV avec siren, sigle, effectif) :
			<%= file_field_tag :file %>
			<%= submit_tag "Import" %>
		<% end %>
	</li>
	<li>
		<%= form_tag import_societe_trainers_path, multipart: true do %>
			Importer depuis "Societe.com" via "Import.io" (CSV avec _pageUrl, rens_jur, dirigeant) :
			<%= file_field_tag :file %>
			<%= submit_tag "Import" %>
		<% end %>
	</li>
	<li>
		<%= form_tag crawl_for_emails_trainers_path, :method => 'get' do %>
			Calculer les mails (Priorité = Paris) :
			<%= number_field_tag :crawls_number, 100 %>
			<%= submit_tag "Calculer", :name => nil %>
		<% end %>
	</li>
	<li><%= link_to "Sauter le dernier OF", skip_trainer_path(Trainer.where.not(nom_dirigeant: nil, crawled_for_email: true).select("*, CASE WHEN trainers.code_postal like '75%' THEN 0 ELSE 1 END AS trainers_order").order("trainers_order ASC").first) %> (en cas de bug)</li>
</ul>